package com.oct.invoicesystem.domain.payment.repository;

import com.oct.invoicesystem.domain.department.model.Department;
import com.oct.invoicesystem.domain.department.repository.DepartmentRepository;
import com.oct.invoicesystem.domain.invoice.model.Invoice;
import com.oct.invoicesystem.domain.invoice.model.InvoiceStatus;
import com.oct.invoicesystem.domain.invoice.repository.InvoiceRepository;
import com.oct.invoicesystem.domain.payment.model.Payment;
import com.oct.invoicesystem.domain.payment.model.PaymentMethod;
import com.oct.invoicesystem.domain.payment.model.PaymentStatus;
import com.oct.invoicesystem.domain.user.model.User;
import com.oct.invoicesystem.domain.user.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * @DataJpaTest — H2 in-memory, schema generated by Hibernate (ddl-auto: create-drop).
 *
 * Tests that {@link PaymentRepository#findProcessedBetween} returns:
 *   - only PROCESSED payments whose processedDate falls within [from, to]
 *   - NOT SCHEDULED payments, even if their processedDate is in range
 *   - NOT PROCESSED payments outside the date range
 */
@DataJpaTest
class PaymentRepositoryTest {

    @Autowired private TestEntityManager em;
    @Autowired private PaymentRepository paymentRepository;
    @Autowired private DepartmentRepository departmentRepository;
    @Autowired private UserRepository userRepository;
    @Autowired private InvoiceRepository invoiceRepository;

    private Invoice invoice;

    @BeforeEach
    void setUp() {
        Department dept = departmentRepository.save(Department.builder()
                .code("TST")
                .nameFr("Test FR")
                .nameEn("Test EN")
                .n1Role("ROLE_TEST")
                .build());

        User user = userRepository.save(User.builder()
                .username("testuser_pr")
                .email("testuser_pr@oct.test")
                .password("hash")
                .firstName("Test")
                .lastName("User")
                .active(true)
                .build());

        // Keep a reference to the first invoice; we'll create a second one for P2
        invoice = invoiceRepository.save(Invoice.builder()
                .referenceNumber("INV-PR-001")
                .amount(new BigDecimal("1000.00"))
                .currency("XAF")
                .issueDate(LocalDate.now())
                .dueDate(LocalDate.now().plusDays(30))
                .supplierName("Test Supplier")
                .supplierEmail("supplier@test.com")
                .status(InvoiceStatus.PAYE)
                .department(dept)
                .submittedBy(user)
                .build());

        em.flush();
    }

    /** Saves a second invoice so that P2 does not violate the OneToOne unique constraint. */
    private Invoice buildSecondInvoice() {
        Department dept = departmentRepository.findAll().get(0);
        User user = userRepository.findAll().get(0);
        Invoice inv2 = invoiceRepository.save(Invoice.builder()
                .referenceNumber("INV-PR-002")
                .amount(new BigDecimal("500.00"))
                .currency("XAF")
                .issueDate(LocalDate.now())
                .dueDate(LocalDate.now().plusDays(30))
                .supplierName("Test Supplier 2")
                .supplierEmail("supplier2@test.com")
                .status(InvoiceStatus.PAYE)
                .department(dept)
                .submittedBy(user)
                .build());
        em.flush();
        return inv2;
    }

    @Test
    void findProcessedBetween_returnsOnlyProcessedPaymentsInRange() {
        Instant now      = Instant.now();
        Instant yesterday = now.minus(1, ChronoUnit.DAYS);
        Instant tomorrow  = now.plus(1,  ChronoUnit.DAYS);

        // P1 — PROCESSED, processedDate = now  →  must be returned
        paymentRepository.save(Payment.builder()
                .invoice(invoice)
                .amountPaid(new BigDecimal("1000.00"))
                .paymentDate(now)
                .paymentMethod(PaymentMethod.VIREMENT)
                .reference("REF-IN-RANGE")
                .status(PaymentStatus.PROCESSED)
                .processedDate(now)
                .build());

        // P2 — PROCESSED, processedDate = 10 days ago  →  must NOT be returned
        // Uses a second invoice to respect the OneToOne unique constraint on invoice_id
        Invoice invoice2 = buildSecondInvoice();
        paymentRepository.save(Payment.builder()
                .invoice(invoice2)
                .amountPaid(new BigDecimal("500.00"))
                .paymentDate(now.minus(10, ChronoUnit.DAYS))
                .paymentMethod(PaymentMethod.CHEQUE)
                .reference("REF-OUT-RANGE")
                .status(PaymentStatus.PROCESSED)
                .processedDate(now.minus(10, ChronoUnit.DAYS))
                .build());

        em.flush();

        List<Payment> results = paymentRepository.findProcessedBetween(yesterday, tomorrow);

        assertThat(results).hasSize(1);
        assertThat(results.get(0).getReference()).isEqualTo("REF-IN-RANGE");
    }

    @Test
    void findProcessedBetween_excludesScheduledPayments() {
        Instant now      = Instant.now();
        Instant yesterday = now.minus(1, ChronoUnit.DAYS);
        Instant tomorrow  = now.plus(1,  ChronoUnit.DAYS);

        // SCHEDULED payment with processedDate in range  →  must NOT appear
        paymentRepository.save(Payment.builder()
                .invoice(invoice)
                .amountPaid(new BigDecimal("1000.00"))
                .paymentDate(now)
                .paymentMethod(PaymentMethod.VIREMENT)
                .reference("REF-SCHED")
                .status(PaymentStatus.SCHEDULED)
                .processedDate(now)
                .build());

        em.flush();

        List<Payment> results = paymentRepository.findProcessedBetween(yesterday, tomorrow);

        assertThat(results).isEmpty();
    }
}
